
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-oci-oci-v1beta1-autonomousdatabases
  failurePolicy: Fail
  name: mautonomousdatabases.kb.io
  rules:
  - apiGroups:
    - oci.oracle.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - autonomousdatabases
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-oci-oci-v1beta1-autonomousdatabases
  failurePolicy: Fail
  name: vautonomousdatabases.kb.io
  rules:
  - apiGroups:
    - oci.oracle.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - autonomousdatabases
  sideEffects: None
